### ISSUE TITLE
Tutorial: change localhost.localdomain to just localhost

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/icat.manual#6]
In the tutorial, we have to use the hostname 'localhost.localdomain' for all the configuration files because this is what Payara defaults to using in its self-signed certificate. It would be better if we could just use 'localhost' in all the configurations as this is/should be the default in all these files. So we need to work out how to tell Payara to create its self-signed certificate using 'localhost' - maybe by changing the output of the `hostname` command using `hostnamectl`:

https://unix.stackexchange.com/questions/12829/how-to-change-the-hostname-of-a-rhel-based-distro
(2nd answer)

**Comment by MRichards99** [comment]
Closing because of #16
